language: node_js
node_js:
- "5.0.0"
- "0.10"
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm prune
before_script:
- npm install --global gulp
- npm install --global karma-cli
env:
  global:
    - secure: EVq5bDA5Y+TxCvfB/HQXPfQia/y8vH3E+ZvZQWqzxz48hReUpYdFVyxAVHrvcuwNqsL8zhgCrPsCsqarMQLCDPth/BABl0GJQpXGoJaTc0nbWl6vYtjRcUrhJtEscmfbVb2RoZraeijtpYF8qh6X/AE4/eJJ63YVT2ENq80KnlyUL2M/ScpPtPhwklCwaOrglkmRVAz7CIy7z9ssV760mz73oFqYCzWsXZXA1jKdKMr4Ta9/X6vDE742gmfgn4XSOug9oA89/TqssEn/b1d1akqt9ujTuNpAcw8kHR3vXKI1njttRXn/mH5kPoZMcqI2Q2tESuGcbMqaVPYDiIJX76e5hvVksKalHvQmUTabiDJcNOl3T2M8mjoAggFoVXNUiDp4UWweCv5U4aYhVsyFbuNoWU1d7SIWLdDc3LJfQX3j/9RFGWVTqyDe/dJNqzOlBO2+sORNpF4LVwJdDQJiplxlRUJORGVv5bwxcJeCwS3FS3Q0BehOu5+B591ZzfFFTSslSjlfWeoxNtvI4qsL9BHVztdARFK85lgQ/moeTst87hq/rQhttdYKrT/kJtT2HcCGdrwH/JxmcGkjn7GZuPPpuHzR1Qir/gUB2eAlvHmqBz9kaYm8ZNdxpQY5gjtTdmUTXVvOZpwrwUxfdNv4T0McNMzi0Z2y0vIfAqMBfd4=
    - secure: wUlzDZJEvX4TxqnH6DSxQHYy6alDYyADaKpUQbuuNYXrTqLqtY6xTPZ4KRN7e3S0lpxUdu2cJWZ5OQ2nrXZ6l+GZDxOa5X/Ls5l35mwJ9+MhPhPng4KWdVd69VbRakQHFd9CprPHRVXDgBCG062NlVGPhWxSnHl/w0s9og0gpQnaxPCME7EPJfmbwMIUYmbirHi0V9I3xbZqGKAcqXRNOeWTbUAzuBRw0DHy3tKvDcDi88w6meTL6J0+M1kS0EaowPq4Xl6dt2Io9K8pL6+KF0mpPfXrjykkqnhwr/ZpXzyHGtbdv544OZLrTwdLH8VVI8AVHxeLFu9AtZWNrADdxt3G0GrcecHTSj6hKdaeGMtRuJzwwDvPif/Auc4nfcLie7LP0C+A0GoJ0wkYtJMQFDnNEDiDgbci6ir3j7AkrJ0cMbSGrgiygWgv8idprESsPItlKOatybMBdy1DN3SIv+3GfF9XGs4OqhWS1F1calwS1GkGIr0xf88wBdxu7PWW7BF0b/5XiPEEpHdHUawUiu69vnm+MSjHTRBGoX1DGW9LxXuxIm1Z1RSy2EIKKmXS5g8O/pqws8ZSY7EAZtsgrLm3mhGKHCTo70/KUSYLxCmb92/xNYRgoKdO6XreOyZeD3N0MDvOHgFRnp3AKuAl+7N2ndjpxLXyNA2OmtpGWH4=
addons:
  sauce_connect: true
